// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5MiW_sTIBiC5UBPnHtRlWQhkQdLBfdc',
    appId: '1:623090011752:web:074515e905331204ffb5dd',
    messagingSenderId: '623090011752',
    projectId: 'photo-anime-b288f',
    authDomain: 'photo-anime-b288f.firebaseapp.com',
    storageBucket: 'photo-anime-b288f.firebasestorage.app',
    measurementId: 'G-6Y2TES711Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ3vbL81ZC0GsQsxCtruPZXQcWnolROHI',
    appId: '1:623090011752:android:504f9fa83147c668ffb5dd',
    messagingSenderId: '623090011752',
    projectId: 'photo-anime-b288f',
    storageBucket: 'photo-anime-b288f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCknz891aFRgVrQ2muEv8uVcG2g4tKJnJI',
    appId: '1:623090011752:ios:302da0e5e47c2167ffb5dd',
    messagingSenderId: '623090011752',
    projectId: 'photo-anime-b288f',
    storageBucket: 'photo-anime-b288f.firebasestorage.app',
    androidClientId:
        '623090011752-8njhm123krful3evfcu999urkiui0es1.apps.googleusercontent.com',
    iosClientId:
        '623090011752-kc6jvbfl3f6rt0kt1dvinaq0nrfemoes.apps.googleusercontent.com',
    iosBundleId: 'com.ai.anime.art.generator.photo.create.pixaiart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt5MiW_sTIBiC5UBPnHtRlWQhkQdLBfdc',
    appId: '1:623090011752:web:6acfbd2023acdf3effb5dd',
    messagingSenderId: '623090011752',
    projectId: 'photo-anime-b288f',
    authDomain: 'photo-anime-b288f.firebaseapp.com',
    storageBucket: 'photo-anime-b288f.firebasestorage.app',
    measurementId: 'G-GSNY91NN2H',
  );
}
